### ISSUE TITLE
Usability: Terminology

### ISSUE THREAD

**Issue by kputh** [OpenSpaceOrg/konopas#5]
Where KonOpas uses text, it speaks of _programme_ (typo included) and _items_ instead of _schedule_ and _sessions_. This can be confusing and distracting for the user, and should be changed.

![bildschirmfoto vom 2018-09-01 um 11 51 50](https://user-images.githubusercontent.com/8649002/44944800-8b39d180-addd-11e8-9baf-3d5dc33b6e02.png)

**Comment by offbyoni** [comment]
Programme is not a typo, it's British English. Changing it to schedule makes sense, though.
